name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # =================================================== #
    # ğŸ‘‡ ì´ permissions ë¸”ë¡ì„ ì¶”ê°€í•˜ì—¬ ì“°ê¸° ê¶Œí•œì„ ë¶€ì—¬í•©ë‹ˆë‹¤.
    permissions:
      contents: write
    # =================================================== #
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate Contribution Calendar" && git push)
