name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 JST 기준 오전 9시에 실행 (UTC 00:00)
    - cron: "0 0 * * *"
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate Contribution Calendar" && git push)
